export const foodTypes = [
    { name: "Hovězí", color: "brown" },
    { name: "Těstovinová", color: "yellow" },
    { name: "Sálaty", color: "green" },
    { name: "Kuřecí", color: "orange" },
    { name: "Rybí", color: "pink" },
    { name: "Luštěniny", color: "lightgreen" },
    { name: "S omáčkou", color: "red" },
    { name: "Polévka", color: "blue" },
    { name: "Smažené", color: "darkbrown" },
    { name: "Kuřecí korma s naan chlebem", color: "yellow" },
    { name: "Grilované kuřecí křidélka s hranolky", color: "orange" },
    { name: "Bramborové", color: "brown" },
    { name: "Asijské", color: "orange" },
    { name: "České", color: "brown" },
    { name: "Zeleninové", color: "green" },
    { name: "Sýrové", color: "yellow" },
    { name: "Rýžové", color: "gray" },
  ];

